### ISSUE TITLE
Network error, timeout of 10000ms exceeded when trying to connect to wallet.

### ISSUE THREAD

**Issue by prajwalkulkarni** [thenewboston-developers/Account-Manager#632]
**Bug Description**
Unable to log in to TNBC wallet. Tried logging in with and without using a nickname. Failing to log in either way.
On further checking the console, several warnings were logged:
```
WebSocket connection to 'ws://54.177.121.3/ws/primary_validator_updated' failed: WebSocket is closed before the connection is established.

```

Error:
```
GET http://54.177.121.3/config net::ERR_CONNECTION_TIMED_OUT

```

The IP address `54.177.121.3` was there by default when I opened the application. I also did try changing the IP Address to that of my network's IPv4 address, wasn't able to log in through that as well.

**Steps to Reproduce**
1. Go to TNB account manager (Windows)
2. Click on connect with the defaults in-place (protocol, IP address, port, and nickname(if applicable).
3.  Toast message pops up saying, Network error and/or timeout of 10000ms exceeded.

**Expected behavior**
To successfully connect to the wallet.

**Actual behavior**
Warning toast message popping up and unable to connect to the wallet.

**Screenshots/Recordings**
![Screenshot (321)_LI](https://user-images.githubusercontent.com/22348265/133217052-e553b0a6-68c4-43e2-a0be-16155122c732.jpg)
![Screenshot (322)_LI](https://user-images.githubusercontent.com/22348265/133217068-82e20c79-ab3c-42d2-b7a8-1ec263aa6bc0.jpg)

**OS and Browser**
 - OS: Windows 10
 - Browser: N/A

**Additional context**
I am not completely sure if it's a bug or am I doing something wrong, if the latter is the case, please help me log in to my wallet. 
I'm currently using TNB account manager 1.0.0-alpha.45
Should I uninstall this version and download the latest version of the app to fix this error?

**Account Number**
Since I'm unable to log in to my wallet, I don't have access to my account number. I Will update once this is fixed/I'm able to gain access to my wallet.

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by hussu010** [comment]
Hi @prajwalkulkarni the error arose because the TNBC network was down. Could you try again? It should be working fine now.

**Comment by prajwalkulkarni** [comment]
Hello @hussu010 , just tried logging in again without making any changes. The issue still persists.

**Comment by hussu010** [comment]
@prajwalkulkarni you must be using old bank IP. Could you try it with `54.183.16.194`?

**Comment by prajwalkulkarni** [comment]
Indeed. Working fine now. By the way, when was the IP updated? And where can I find news about such updates?

**Comment by hussu010** [comment]
@prajwalkulkarni you should follow the official discord server of thenewboston to get updated with the new changes.
https://discord.com/invite/thenewboston

**Comment by prajwalkulkarni** [comment]
Joined, thanks for the information. Closing the issue now.
